version: '3.9'
services:
  # Configs #
  web:
    container_name: web_api
    hostname: web_api
    build: .
    ports: 
      - '8000:5000'
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
    networks:
      - default
  database:
    image: mongo:latest
    container_name: mongodb
    hostname: host-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root-master
      MONGO_INITDB_ROOT_PASSWORD: password-master
      MONGO_INITDB_DATABASE: db-master
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo-volume:/data/db
      - ./mongo-volume/log:/var/log/mongodb/
    ports:
      - '27017-27019:27017-27019'
    networks:
      - default
volumes:
    persistent: